apiVersion: lib.projectsveltos.io/v1alpha1
kind: EventSource
metadata:
 name: todo-app-health
spec:
 collectResources: false
 group: "apps"
 version: "v1"
 kind: "Deployment"
 namespace: todo
 script: |
  function evaluate()
    hs = {}
    hs.matching = false
    hs.message = ""
    if obj.metadata.name == "todo-gitops" then
      if obj.status ~= nil then
        if obj.status.availableReplicas ~= nil then
          if obj.status.availableReplicas == obj.spec.replicas then
            hs.matching = true
          end
        end
      end
    end
    return hs
  end
---
apiVersion: lib.projectsveltos.io/v1alpha1
kind: EventBasedAddOn
metadata:
 name: insert-data
spec:
 sourceClusterSelector: env=fv
 eventSourceName: todo-app-health
 stopMatchingBehavior: LeavePolicies
 policyRefs:
 - name: todo-insert-data
   namespace: default
   kind: ConfigMap