apiVersion: lib.projectsveltos.io/v1alpha1
kind: EventSource
metadata:
 name: postgresql-job-completed
spec:
 collectResources: false
 group: "batch"
 version: "v1"
 kind: "Job"
 namespace: todo
 script: |
  function evaluate()
    hs = {}
    hs.matching = false
    hs.message = ""
    if obj.metadata.name == "todo-table" then
      if obj.status ~= nil then
        if obj.status.succeeded == 1 then
          hs.matching = true
        end
      end
    end
    return hs
  end
---
apiVersion: lib.projectsveltos.io/v1alpha1
kind: EventBasedAddOn
metadata:
 name: deploy-todo-app
spec:
 sourceClusterSelector: env=fv
 eventSourceName: postgresql-job-completed
 stopMatchingBehavior: LeavePolicies
 policyRefs:
 - name: todo-app
   namespace: default
   kind: ConfigMap